# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.CharField(default='Title', max_length=40),
        ),
    ]
